// <auto-generated />
namespace VinlandSaga.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class lab622 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lab622));
        
        string IMigrationMetadata.Id
        {
            get { return "202505271927523_lab622"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
